train_name: whisper
audio_max_length: 160000 # 10 sec
text_max_length: null
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 1
precision: 16-mixed

model_name: small
learning_rate: 2.5e-5
batch_size: 32
num_train_steps: 45000
warmup_steps: 7500
gradient_accumulation_steps: 1

monitor: 'val/cer_student'  
noise_prob: 0.0
noise_snr_train: 0

spec_augment: ""
dropout_rate: 0 

lang: zh
resume_training: False
# pt_ckpt: 'whisper_taigi_small/step-78000-cer=0.1811-wer=0.6140.ckpt'
# pt_ckpt: 'trans_asr_taigi/step-176000-cer_at=0.1584.ckpt'
train_id: hermes_asr_taigi_lora_add_adapters_282_all_hiddens

transasr_ckpt: 'trans_asr_taigi/step-176000-cer_at=0.1584.ckpt'
# base_whisper_ckpt: 'models/checkpoints/whisper_taigi_small/step-78000-cer=0.1811-wer=0.6140.ckpt'
kd_alpha: 0.2
kd_beta: 0.8
kd_gamma: 0.2
kd_temp: 0.2

# text
add_gated_x_attn: 1 # 0 for False, 1 for True
num_langs: 1

log_output_dir: "slurm/train_text_slurm"
check_output_dir: "models/checkpoints"
filename: "step-{step:05d}-cer_student={val/cer_student:.4f}"
